@q36:
DATA VAL "1936"
DATA "3.00pm","Programme Summary"
DATA "   followed by","Christmas Turkey"
DATA "3.15pm","News Reel"
DATA "3.25pm","A Lonely Christmas Arctic"
DATA "3.30pm","Picture Page (14th) Christmas Number"
DATA "4.00pm","Closedown"
DATA "  ",""
DATA "9.00pm","Christmas Carols"
DATA "9.10pm","A Seasonal Tour through the Empire"
DATA "9.20pm","Some Unusual Christmases"
DATA "9.30pm","News Reel"
DATA "9.35pm","Television Party"
DATA "10.00pm","Closedown"
DATA "END"
