@q49:
DATA VAL "1949"
DATA "10.50am","Christmas Day Parade Service"
DATA "  ","from the Royal Hospital Chapel, Chelsea"
DATA "11.45am","Closedown"
DATA "3.20pm","Film : Little Lord Fauntleroy (1936)"
DATA "5.00pm","Closedown"
DATA "6.30pm","Toad of Toad Hall"
DATA "8.30pm","Closedown"
DATA "9.00pm","Miranda"
DATA "  ","a comedy by Peter Blackmore"
DATA "10.40pm","News (sound only)"
DATA "10.55pm","Closedown"
DATA "END"
