@q53:
DATA VAL "1953"
DATA "11.00am","Christmas Day Service "
DATA "  ","from Church of St. Julian, Somerset"
DATA "12.00pm","Closedown"
DATA "3.15pm","Christmas Journey Round the World"
DATA "4.15pm","Watch with Mother : Andy Pandy"
DATA "4.30pm","Closedown"
DATA "5.00pm","The Walt Disney Christmas Show"
DATA "5.55pm","Closedown"
DATA "7.25pm"," Weather Chart"
DATA "7.30pm","Christmas Party"
DATA "  ","Your Hosts McDonald and Leslie Michell,"
DATA "  ","Terry-Thomas, Norman Wisdom, Arthur Askey,"
DATA "  ","The Beverley Sisters, Julie Andrews,"
DATA "  ","Chan Canasta, Shirley Abicair,"
DATA "  ","John Slater and Max Bygraves"
DATA "9.15pm","Newsreel"
DATA "9.30pm","Interlude"
DATA "9.40pm","Dear Octopus"
DATA "  ","A comedy by Dodie Smith."
DATA "  ","Starring Helen Haye, Malcolm Keen"
DATA "  ","and Rachel Gurney"
DATA "11.25pm","News (sound only)"
DATA "11.40pm","Closedown"
DATA "END"
