@q55:
DATA VAL "1955"
DATA "11.00am","Welcome to the New Born King"
DATA "12.00pm","Closedown"
DATA "3.00pm","A Christmas Message to the"
DATA "  ","Commonwealth from H.M. The Queen"
DATA "  ","(sound only)"
DATA "3.15pm","A Christmas Visit to Disneyland"
DATA "4.45pm","Watch with Mother : Andy Pandy"
DATA "5.00pm","Children's Television Excerpts"
DATA "7.30pm","News, The Weather"
DATA "7.45pm","Music for You"
DATA "9.00pm","Christmas Box"
DATA "9.45pm","Bird in Hand"
DATA "11.15pm","Today in Bethlehem"
DATA "11.25pm","News Summary, The Weather"
DATA "   then","Closedown"
DATA "END"
