@q60:
DATA VAL "1960"
DATA "9.29am","Headline News"
DATA "9.30am","On Christmas Day in the Morning"
DATA "10.00am","The Perry Como Music Hall"
DATA "10.45am","Christmas Morning Service "
DATA "11.45am","Max Jaffa invites you to a Christmas"
DATA "  ","party with The Trios"
DATA "12.05pm","Film :"
DATA "  ","The Adventures of Hiram Holliday :"
DATA "  ","Vanishing House"
DATA "12.30pm","Sing We Now of Christmas! "
DATA "1.00pm","The Queen"
DATA "1.09pm","The George Mitchell Glee Club"
DATA "1.44pm","Wells Fargo"
DATA "2.09pm","Walt Disney"
DATA "3.25pm","Appeal -"
DATA "  ","British Wireless for the Blind Fund"
DATA "3.30pm","Billy Smart's Circus"
DATA "4.30pm","What's My Line? "
DATA "5.00pm","Tonight with Belafonte"
DATA "5.50pm","The News "
DATA "   followed by","Weather"
DATA "6.00pm","Christmas Night with the Stars"
DATA "7.15pm","Film : The Prisoner of Zenda (1937)"
DATA "8.50pm","The Sunday Night Play :"
DATA "  ","Tuppence in the Gods"
DATA "10.20pm","Christmas at Dean's Yard"
DATA "10.40pm","Late Night News"
DATA "10.45pm","Celebrity Recital"
DATA "11.05pm","Weather and Closedown"
DATA "END"
