@q66:
DATA VAL "1966"
DATA "9.30am","Welcome Christmas"
DATA "  ","Judith Chalmers and Michael Aspel"
DATA "10.10am","Mak the Sheep-Stealer"
DATA "11.00am","Christmas Morning Service"
DATA "  ","from Christ Church, Cotham, Bristol"
DATA "12.00pm","Meet the Kids in hospital"
DATA "  ","at Christmas. With Leslie Crowther"
DATA "  ","and George Chisholm"
DATA "12.44pm","The Weather Man"
DATA "12.45pm","The Lucy Show"
DATA "  ","starring Lucille Ball"
DATA "1.10pm","The Andy Williams Show"
DATA "2.00pm","The Royal Palaces of Britain"
DATA "3.00pm","The Queen"
DATA "3.05pm","Billy Smart's Circus"
DATA "4.00pm","Disney Time"
DATA "4.40pm","Aladdin and His Wonderful Lamp"
DATA "  ","Arthur Askey, Angela Richards, Roy Castle"
DATA "6.05pm","The News and The Weatherman"
DATA "6.10pm","Robert Dougall"
DATA "  ","appeals for the Royal National"
DATA "  ","Institute 0for the Deaf"
DATA "6.15pm","Journey to Bethlehem"
DATA "6.45pm","Christmas Carols"
DATA "  ","from King's College, Cambridge"
DATA "7.25pm","The Black and White Minstrel Show"
DATA "8.00pm","The Ken Dodd Show"
DATA "8.45pm","Film : The Comancheros (1961)"
DATA "10.25pm","The News and Weather"
DATA "10.30pm","Dr Finlay's Casebook"
DATA "11.20pm","The Weather Man"
DATA "11.22pm","The Christmas Story"
DATA "END"
