@q69:
DATA VAL "1969"
DATA "9.00am","On Christmas Day in the Morning"
DATA "  ","with Michael Aspel and Sheila Tracy"
DATA "9.30am","A Spoonful of Sugar"
DATA "10.00am","The News and Weather"
DATA "10.05am","Tom and Jerry"
DATA "10.15am","The Doctors"
DATA "10.35am","Christmas Morning Service"
DATA "  ","from St George's Chapel, Windsor Castle"
DATA "11.45am","Rolf Harris"
DATA "12.30pm","Royal Family"
DATA "  ","documentary by Richard Cawston"
DATA "2.15pm","Top of the Pops"
DATA "  ","The Beatles, Blue Mink, Creedence"
DATA "  ","Clearwater Revival, Fleetwood Mac"
DATA "3.00pm","Billy Smart's Circus Spectacular"
DATA "4.10pm","Disney Time with Julie Andrews"
DATA "5.00pm","BBC Television's Christmas pantomime:"
DATA "  ","Cinderella"
DATA "6.30pm","The Main News with Robert Dougall"
DATA "followed by","Weather"
DATA "6.40pm","Save the Children"
DATA "  ","appeal by Barbara Mullen"
DATA "6.45pm","Christmas Night with the Stars"
DATA "  ","introduced by Val Doonican"
DATA "8.15pm","The Morecambe and Wise Christmas Show"
DATA "9.15pm","Film : McLintock (1963)"
DATA "11.15pm","Tony Bennett"
DATA "  ","and the Count Basie Orchestra"
DATA "12.05am","And Was Made Black"
DATA "END"
