@q73:
DATA VAL "1973"
DATA "9.35am","Along the Trail"
DATA "9.50am","The Selfish Giant"
DATA "10.15am","News Headlines"
DATA "10.20am","Christmas Morning Service"
DATA "11.25am","Harry Secombe"
DATA "11.30am","A Stocking Full of Stars"
DATA "1.30pm","The Black and White Minstrel Show"
DATA "2.15pm","Top of the Pops"
DATA "  ","with Tony Blackburn and Noel Edmonds"
DATA "3.00pm","The Queen"
DATA "3.15pm","Billy Smart's Christmas Circus"
DATA "4.20pm","Christmas Pantomime : Robin Hood"
DATA "5.55pm","News with Robert Dougall"
DATA "6.05pm","Bruce Forsyth and the Generation Game"
DATA "7.05pm","The Mike Yarwood Christmas Show"
DATA "7.35pm","Morecambe and Wise Christmas Show"
DATA "8.35pm","Film : The Odd Couple (1968)"
DATA "10.20pm","News with Robert Dougall"
DATA "   followed by","Weather"
DATA "10.30pm","Gala Performance"
DATA "11.35pm","Lost Hearts"
DATA "12.10am","Weather"
DATA "   followed by","Closedown"
DATA "END"
