@q77:
DATA VAL "1977"
DATA "8.55am","Star Over Bethlehem (R)"
DATA "9.55am","Playboard (R)"
DATA "10.10am","Michael Bentine"
DATA "10.15am","Christmas Worship"
DATA "11.13am","Weatherman"
DATA "11.15am","The Bear Who Slept Through Christmas"
DATA "11.40am","Film : National Velvet (1944)"
DATA "1.40pm","Are You Being Served?"
DATA "  ","The Father Christmas Affair (R)"
DATA "2.10pm","Top of the Pops"
DATA "  ","with Noel Edmonds, Kid Jensen"
DATA "3.00pm","The Queen"
DATA "3.10pm","Billy Smart's Christmas Circus"
DATA "4.10pm","Film : The Wizard of Oz (1939)"
DATA "5.50pm","Basil Through the Looking Glass"
DATA "6.20pm","Evening News with Angela Rippon"
DATA "   followed by","Weather with Michael Fish"
DATA "6.25pm","Songs of Praise Special"
DATA "7.15pm","Bruce Forsyth and The Generation Game"
DATA "8.20pm","Mike Yarwood Christmas Show"
DATA "8.55pm","Morecambe and Wise Christmas Show"
DATA "10.00pm","News with Angela Rippon"
DATA "   followed by","Weather"
DATA "10.05pm","Film : Funny Girl (1968)"
DATA "12.30am","Weatherman"
DATA "12.31am","Closedown"
DATA "END"
