@q80:
DATA VAL "1980"
DATA "8.55am","Watch"
DATA "9.25am","Mr Benn"
DATA "9.40am","The Pink Panther Show"
DATA "10.00am","Morning Worship "
DATA "11.00am","Weather with Jim Bacon"
DATA "11.05am","Film : The Wonderful World of the"
DATA "  ","Brothers Grimm (1962)"
DATA "1.10pm","Carols from Warwick Castle"
DATA "2.00pm","Top of the Pops"
DATA "  ","including Abba, Blondie, David Bowie"
DATA "3.00pm","The Queen"
DATA "3.10pm","Film :"
DATA "  ","20,000 Leagues Under the Sea (1954) (P)"
DATA "5.15pm","The Paul Daniels Magic Show"
DATA "6.05pm","Evening News with Angela Rippon"
DATA "6.10pm","Larry Grayson's Generation Game"
DATA "7.15pm","Dallas"
DATA "8.05pm","The Mike Yarwood Christmas Show"
DATA "8.45pm","Film : Airport 1975 (1974) (P)"
DATA "10.30pm","Main News with Angela Rippon "
DATA "   followed by","Holiday Weather with Jim Bacon"
DATA "10.40pm","Parkinson at Christmas"
DATA "11.40pm","Christmas Comedy Classic"
DATA "  ","Fawlty Towers : Gourmet Nights"
DATA "12.10am","Weather"
DATA "END"
