@q81:
DATA VAL "1981"
DATA "8:40am","Star Over Bethlehem"
DATA "9:40am","The Flumps (R)"
DATA "9:55am","Rolf at Christmas"
DATA "10:30am","Christmas Morning Service"
DATA "11:47am","Weather with Jack Scott"
DATA "11:50am","The Donald Duck Story"
DATA "12:30pm","Film : tom thumb (1958)"
DATA "2:00pm","Top of the Pops"
DATA "  ","with David Jensen"
DATA "3:00pm","The Queen speaks to the Commonwealth"
DATA "3:10pm","Larry Grayson's Generation Game"
DATA "4:10pm","Film :"
DATA "  ","In Search of the Castaways (1961)"
DATA "5:45pm","Jim'll Fix It"
DATA "6:25pm","Evening News with Moira Stuart"
DATA "   followed by","Weatherman"
DATA "6:35pm","Paul Daniels' Magical Christmas"
DATA "7:15pm","Last of the Summer Wine"
DATA "7:45pm","The Two Ronnies"
DATA "8:35pm","Dallas"
DATA "9:25pm","Film : Loophole (1980)"
DATA "11:05pm","Main News with Moira Stuart"
DATA "   followed by","Holiday Weather"
DATA "  ","with Jack Scott"
DATA "11:15pm","Parkinson on Comedy"
DATA "12:15am","Christmas Night with The Spinners"
DATA "12:45am","Weather"
DATA "12:50am","Closedown"
DATA "END"
