@q82:
DATA VAL "1982"
DATA "8:40am","The All-New Pink Panther Show"
DATA "9:00am","Carols from Buckfast"
DATA "9:45am","Christmas Parade"
DATA "10:35am","Christmas Morning Service"
DATA "11:38am","Weather with Michael Fish"
DATA "11:40am","Raccoons on Ice"
DATA "12:05pm","Film : Mister Quilp (1975)"
DATA "2:00pm","Top of the Pops"
DATA "  ","Christmas Party with Peter Powell"
DATA "3:00pm","The Queen speaks to the Commonwealth"
DATA "3:05pm","Film : International Velvet (1978)"
DATA "5:10pm","News with Jan Leeming Weatherman"
DATA "5.20pm","Jim'll Fix It"
DATA "6:00pm","The Paul Daniels Magic Christmas Show"
DATA "6.55pm","Last of the Summer Wine"
DATA "7:30pm","The Two Ronnies Christmas Show"
DATA "8:15pm","Film : Death on the Nile (1978)"
DATA "10:30pm","News with Jan Leeming, Weatherman"
DATA "10:40pm","Perry Como"
DATA "11:30pm","Ghost Story for Christmas :"
DATA "  ","The Signalman"
DATA "12:10am","Christmas Night with The Spinners"
DATA "12:40am","Weather"
DATA "12:45am","Closedown"
DATA "END"
