@q83:
DATA VAL "1983"
DATA "8:35am","The Christmas Raccoons"
DATA "9:00am","Carols from Newby Hall"
DATA "9:50am","Away In a Manger"
DATA "10:20am","Christmas Morning Family Service"
DATA "11:17am","Weather"
DATA "11:20am","The Little Convict"
DATA "12:35pm","Ziggy's Gift"
DATA "1:00pm","Bugs Bunny in Abominable Snow Rabbit"
DATA "1:05pm","Film : Glitterball (1977)"
DATA "2:00pm","Top of the Pops"
DATA "  ","Michael Jackson, Shakin' Stevens"
DATA "3:00pm","The Queen"
DATA "3:15pm","Blankety Blank"
DATA "3:50pm","Film : Treasure Island (1950) (P)"
DATA "5:25pm","News with Jan Leeming"
DATA "   followed by","Weather"
DATA "5:35pm","Jim'll Fix It"
DATA "6:15pm","Songs of Praise Special"
DATA "7.15pm","The Two Ronnies"
DATA "8:05pm","All Creatures Great and Small"
DATA "9:35pm","Only Fools and Horses"
DATA "  ","Thicker Than Water"
DATA "10:05pm","News with Jan Leeming and Weatherman"
DATA "10:15pm","Film :"
DATA "  "," Better Late Than Never (1983) (P)"
DATA "11.45pm","The Spinners at York"
DATA "12.15am","Weather"
DATA "END"
