@q88:
DATA VAL "1988"
DATA "6:55am","Now It's Christmas"
DATA "  ","The Christmas Toy"
DATA "7:45am","The Christmas Raccoons"
DATA "8:10am","The Nativity Play"
DATA "8:20am","Playbus"
DATA "8:45am","The Pink Panther Show"
DATA "9:10am","Charlie's Christmas Project"
DATA "9:35am","Umbrella Christmas Special"
DATA "10:00am","Christmas Worship"
DATA "11:00am","Christmas Morning with Noel"
DATA "12:05pm","It's a Charity Knockout"
DATA "1:00pm","EastEnders"
DATA "2:00pm","Top of the Pops Christmas Show"
DATA "3:00pm","HM The Queen"
DATA "3:10pm","Film : Back to the Future (1985) (P)"
DATA "5:05pm","Only Fools and Horses"
DATA "6:25pm","News and Weather"
DATA "6:30pm","Songs of Praise Special"
DATA "  ","Cliff Richard and Sally Magnusson"
DATA "7:15pm","Bread"
DATA "8:30pm","The Russ Abbot Christmas Show"
DATA "9:10pm","News and Weather"
DATA "9:20pm","Film : Silverado (1985)"
DATA "11:30pm","The Gospel According to St Matthew"
DATA "11:40pm","Broadway Musicals : Carousel (1956)"
DATA "1:45am","Weather"
DATA "1:50am","Closedown"
DATA "END"
