@q95:
DATA VAL "1995"
DATA "6.00am","Podddington Peas (R)"
DATA "6.05am","Bump's Christmas Story (R)"
DATA "6.15am","Moomin"
DATA "6.40am","White Christmas"
DATA "7.10am","Playdays (R)"
DATA "7.30am","PJ's Unfunnybunny Christmas"
DATA "7.55am","McGee and Me (R)"
DATA "8.15am","The Flintstones"
DATA "9.25am","The Movie Game"
DATA "10.00am","Christmas Day in the Morning"
DATA "  ","Harry Secombe, Ruth Madoc, Clive Mantle and BBC Choirgirl of the Year Tabitha Watling"
DATA "10.55am","Film : The Neverending Story (1984)"
DATA "12.25pm","Neighbours"
DATA "12.50pm","News and Weather"
DATA "12.55pm","Top of the Pops"
DATA "  ","with Bjork and Jack Dee"
DATA "1.55pm","Only Fools and Horses :"
DATA "  ","Mother Nature's Son"
DATA "  ","(Christmas edition from 1992) (R)"
DATA "3.00pm","The Queen"
DATA "3.10pm","Noel's Christmas Presents"
DATA "  ","With Cliff Richard and Riverdance"
DATA "4.20pm","News, Weather"
DATA "4.30pm","Film : Hook (1991) (P)"
DATA "6.45pm","Auntie's Brand New Bloomers"
DATA "7.30pm","EastEnders"
DATA "8.00pm","Keeping Up Appearances"
DATA "8.30pm","EastEnders"
DATA "  ","Part 2"
DATA "9.00pm","One Foot in the Grave"
DATA "","The Wisdom of the Witch"
DATA "10.00pm","News with Peter Sissons"
DATA "   followed by","Weather with Rob McElwee"
DATA "10.10pm","Film : Indecent Proposal (1993) (P)"
DATA "12.00pm","I Hate Christmas"
DATA "12.05am","The Greatest Music Party in the World with David Bowie, Rod Stewart,"
DATA "  ","Diana Ross, Soul II Soul, Lightning Seeds,"
DATA "  ","Des'ree, Echobelly, Alanis Morissette,"
DATA "  ","Alanan Myles, Curtis Stigers, Diana King"
DATA "1.35am","Weather"
DATA "1.40am","Closedown"
DATA "END"

