@q97:
DATA VAL "1997"
DATA "6.00am","Christopher the Christmas Tree (R)"
DATA "6.25am","Santa's First Christmas (R)"
DATA "6.50am","The Legend of Prince Valiant (R)"
DATA "7.15am","Eek! the Cat (R)"
DATA "7.35am","Free Willy"
DATA "8.00am","A Monster Christmas (R)"
DATA "8.30am","The Demon Headmaster Takes Over TV"
DATA "9.20am","Casper"
DATA "9.40am","Teletubbies Christmas Carols"
DATA "10.05am","Christmas at the Castle"
DATA "11.05am","Film : Willy Wonka and the Chocolate"
DATA "  ","Factory (1971)"
DATA "12.40pm","Peter and the Wolf"
DATA "1.10pm","News and Weather"
DATA "1.15pm","Top of the Pops"
DATA "2.15pm","The Two Ronnies Christmas Show"
DATA "3.00pm","The Queen"
DATA "3.10pm","Noel's Christmas Presents"
DATA "4.10pm","Film : The Flintstones (1994)"
DATA "5.30pm","Animal Hospital"
DATA "6.00pm","Auntie's New Festive Bloomers"
DATA "6.40pm","News"
DATA "6.50pm","Film : The Mask (1994)"
DATA "   followed by","A Perfect Day for Christmas"
DATA "8.30pm","EastEnders"
DATA "9.00pm","One Foot in the Grave"
DATA "10.10pm","News"
DATA "   followed by","Weather"
DATA "10.20pm","Men Behaving Badly"
DATA "11.05pm","They Think It's All Over"
DATA "11.40pm","I Hate Christmas Too!"
DATA "11.45pm","Film : Airplane! (1980)"
DATA "1.10am","Film : Carry On Loving (1970)"
DATA "2.40am","News 24"
DATA "END"
