@q98:
DATA VAL "1998"
DATA "6.00am","Teletubbies (R)"
DATA "6.25am","Noddy in Toyland"
DATA "7.20am","PJ's Unfunny Bunny Christmas (R)"
DATA "7.45am","Scrooge Koala's Christmas"
DATA "8.10am","Alvin and the Chipmunks (R)"
DATA "8.35am","To me......to You"
DATA "  ","festive challenges with"
DATA "  ","the Chuckle Brothers"
DATA "9.00am","Rotten Ralph"
DATA "9.30am"," Teletubbies Nativity Play"
DATA "10.00am","Celebrate Christmas"
DATA "  ","Deborah McAndrew presents festive music"
DATA "11.00am","Film : Miracle on 34th Street"
DATA "  ","(1994) (P)"
DATA "12.50pm"," Top of the Pops"
DATA "1.50pm"," News and Weather"
DATA "1.55pm","The Morecambe and Wise Christmas Show"
DATA "  ","starring Andre Previn, Hannah Gordon"
DATA "3.00pm","The Queen"
DATA "3.10pm","Noel's Christmas Presents"
DATA "4.10pm","Animal Hospital"
DATA "4.15pm","The First Snow of Winter"
DATA "5.15pm","News, Weather"
DATA "5.25pm","EastEnders"
DATA "5.55pm","Auntie's Spanking New"
DATA "  ","Christmas Bloomers"
DATA "  ","Terry Wogan reveals more moments"
DATA "6.30pm","Changing Rooms at Christmas"
DATA "  ","Carol Smillie is on the isle of Arran"
DATA "7.00pm","Film : Babe (1995) (P)"
DATA "8.30pm","EastEnders"
DATA "9.00pm","Before They Were Famous III"
DATA "  ","with Angus Deayton"
DATA "9.40pm","News with Huw Edwards"
DATA "   followed by","Weather with Michael Fish"
DATA "9.50pm","Men Behaving Badly"
DATA "10.35pm","They Think It's All Over"
DATA "  ","hosted by Nick Hancock"
DATA "11.10pm","A Many Splintered Thing"
DATA "11.40pm","The People's Nativity"
DATA "  ","Tom Jones, Barbara Windsor,"
DATA "  ","Alan Titchmarsh, Des Lynam"
DATA "11.45pm","Robbie Williams :"
DATA "  ","For One Night Only"
DATA "12.35am","Film : Carry on Girls (1973)"
DATA "2.05am","BBC News 24"
DATA "END"
