@q01:
DATA VAL "2001"
DATA "5.45am","Film : We're Back! a Dinosaur's"
DATA "  ","Story (1993)"
DATA "6.50am","CBBC Hollyday Hot"
DATA "6.55am","The Woody Woodpecker Show"
DATA "7.15am","Blue Peter (R)"
DATA "7.45am","Rugrats (R)"
DATA "8.15am","The Wild Thornberrys"
DATA "9.30am","Second Star to the Left (R)"
DATA "10.00am","God's Surprise"
DATA "11.00am","The Two Ronnies Christmas Show"
DATA "11.45am","Film : Casper (1995)"
DATA "1.20pm","News ; Weather"
DATA "1.30pm","Top of the Pops"
DATA "2.30pm","Hamilton Mattress"
DATA "3.00pm","The Queen "
DATA "3.10pm","Rolf's Merry Christmas"
DATA "4.00pm","Dazzling Bloomers"
DATA "4.30pm","News ; Weather"
DATA "4.40pm","Film : Toy Story (1995) "
DATA "5.55pm","EastEnders"
DATA "6.25pm","The Lost World"
DATA "7.40pm","Alistair McGowan's Big Impression"
DATA "8.20pm","BBC News with George Alagiah "
DATA "   followed by","Weather with Isobel Lang"
DATA "8.30pm","EastEnders"
DATA "9.05pm","Only Fools and Horses"
DATA "10.15pm","Before They Were Famous"
DATA "10.55pm","Film : Sliding Doors (1997) "
DATA "12.30am","Battersea to Bethlehem :"
DATA "  ","a Christmas Story"
DATA "12.35am","Film : Steptoe and Son"
DATA "  ","Ride Again (1973)"
DATA "2.15am","Sign Two : When Louis Met"
DATA "  ","the Hamiltons (R)"
DATA "3.35am","BBC News 24"
DATA "END"
