@q14:
DATA VAL "2014"
DATA "6.00am","Breakfast"
DATA "9.00am","The Gruffalo (R)"
DATA "9.30am","On Angel Wings (R)"
DATA "10.00am","Come And Join The Celebration"
DATA "11.00am","Only Fools and Horses : A Royal Flush"
DATA "12.00pm","Wallace & Gromit : A Grand Day Out"
DATA "12.25pm","Film : Gnomeo and Juliet (2011)"
DATA "1.40pm","Shaun the Sheep (R)"
DATA "1.50pm","BBC News and Weather"
DATA "2.00pm","Top of the Pops"
DATA "3.00pm","The Queen"
DATA "3.10pm","Film : Puss in Boots (2011)"
DATA "4.40pm","BBC News and Weather"
DATA "5.00pm","Strictly Come Dancing"
DATA "  ","Christmas Special"
DATA "6.15pm","Doctor Who : Last Christmas"
DATA "7.15pm","Miranda"
DATA "7.50pm","Call the Midwife"
DATA "9.00pm","EastEnders"
DATA "10.05pm","Mrs Brown's Boys"
DATA "10.40pm","Michael McIntyre's"
DATA "  ","Very Christmassy Christmas Show"
DATA "11.40pm","BBC News and Weather"
DATA "11.55pm","On Christmas Night"
DATA "12.00pm","Not Going Out (R)"
DATA "12.45am","Would I Lie to You? At Christmas (R)"
DATA "1.15am","George Michael","  ","at the Palais Garnier, Paris (R)"
DATA "2.15am","Film : The Heartbreak Kid (2007)"
DATA "3.55am","Skiing Weatherview"
DATA "4.00am","BBC News"
DATA "END"
