@q17:
DATA VAL "2017"
DATA "6.00am","Breakfast"
DATA "9.00am","Cbeebies Presents"
DATA "  ","The Snow Queen (R)"
DATA "9.45am","Go Jetters (R)"
DATA "10.00am","Christmas Day Eucharist"
DATA "  ","Christmas Morning from All Saints Fulham"
DATA "11.00am","The Madagascar Penguins:"
DATA "  ","A Christmas Caper (R)"
DATA "11.10am","Snow Chick : A Penguins Tale (R)"
DATA "12.10pm","BBC News/Weather"
DATA "12.20pm","Top of the Pops Christmas"
DATA "  ","Fearne Cotton and Clara Amfo"
DATA "1.20pm","Film : Toy Story 3 (2010)"
DATA "3.00pm","The Queen"
DATA "3.10pm","Film : Cinderella (2015) (P)"
DATA "4.45pm","The Highway Rat"
DATA "5.15pm","BBC News/Weather"
DATA "5.30pm","Doctor Who : Twice Upon a Time"
DATA "6.30pm","Strictly Come Dancing"
DATA "  ","Christmas Special"
DATA "  ","Robbie Savage, Katie Derham, Jeremy Vine,"
DATA "  ","Kimberley Walsh, Judy Murray, Colin Jackson"
DATA "7.40pm","Call the Midwife Christmas Special"
DATA "9.00pm","EastEnders"
DATA "10.00pm","Mrs Brown's Boys"
DATA "10.35pm","300 Years of French and Saunders"
DATA "11.25pm","BBC News/Weather"
DATA "11.40pm","On Christmas Night"
DATA "  ","reading by Colin Salmon"
DATA "11.45pm","Have I Got a Bit More News for You"
DATA "12.30am","Darcey Bussell :"
DATA "  ","Looking for Fred Astaire (R)"
DATA "1.30am","Weather for the Week Ahead"
DATA "1.35am","BBC1 joins the BBC News channel"
DATA "END"
