@q20:
DATA VAL "2020"
DATA "6.00am","Breakfast"
DATA "8.55am","The Gruffalo (R)"
DATA "9.25am","The Gruffalo's Child (R)"
DATA "9.50am","Lou"
DATA "10.00am","Christmas Day Eucharist"
DATA "11.00am","The Snail and the Whale (R)"
DATA "11.25am","Zog (R)"
DATA "11.55am","Top of the Pops Christmas Special"
DATA "12.55pm","BBC News, Weather"
DATA "1.10pm","Inner Workings"
DATA "1.15pm","Film : Early Man (2018) (P)"
DATA "2.35pm","Zog and the Flying Doctors"
DATA "3.00pm","The Queen"
DATA "3.10pm","Film : Coco (2017) (P)"
DATA "   followed by","BBC News Update"
DATA "4.45pm","Strictly Come Dancing"
DATA "  ","Christmas Special"
DATA "6.00pm","Michael McIntyre's Christmas Wheel"
DATA "7.00pm","Blankety Blank Christmas Special"
DATA "7.40pm","Call the Midwife Christmas Special"
DATA "9.10pm","EastEnders"
DATA "10.00pm","Mrs Brown's Boys"
DATA "10.40pm","The Vicar of Dibley (R)"
DATA "11.25pm","BBC News, Weather"
DATA "11.40pm","On Christmas Night"
DATA "11.45pm","Paul McCartney at the Cavern Club"
DATA "1.45am","Film : Absolutely Fabulous (2016)"
DATA "2.40am","Weather for the Week Ahead"
DATA "2.45am","BBC News"
DATA "END"
