@q23:
DATA VAL "2023"
DATA "6.00am","Breakfast"
DATA "8.50am","The Gruffalo (R)"
DATA "9.15am","How to Train Your Dragon :"
DATA "  ","Homecoming (R)"
DATA "9.40am","The Boy, The Mole, The Fox"
DATA "  ","and The Horse (R)"
DATA "10.15am","Christmas Morning Service"
DATA "  ","from Manchester Cathedral"
DATA "11.15am","Film : Cinderella (2015)"
DATA "12.55pm","Film : The Addams Family 2 (2021) (P)"
DATA "2.20pm","BBC Weekend News, Weather"
DATA "2.35pm","Tabby McTat"
DATA "3.00pm","The King's Christmas Broadcast"
DATA "3.10pm","Film : Toy Story 4 (2019) (P)"
DATA "4.40pm","Strictly Come Dancing"
DATA "  ","Christmas Special"
DATA "5.55pm","Doctor Who : The Church on Ruby Road"
DATA "6.50pm","Michael McIntyre's Christmas Wheel"
DATA "7.45pm","Ghosts Christmas Special"
DATA "8.15pm","Call the Midwife Christmas Special"
DATA "9.45pm","EastEnders"
DATA "10.45pm","Mrs Brown's Boys Christmas Special"
DATA "11.15pm","BBC News, Weather"
DATA "11.35pm","On Christmas Night"
DATA "11.40pm","The Vicar of Dibley (R)"
DATA "12.35am","Film : Yesterday (2019)"
DATA "2.25am","Have I Got a Bit More News for You (R)"
DATA "3.10am","Weather for the Week Ahead"
DATA "3.15am","BBC News"
DATA "END"
